### ISSUE TITLE
RGATConv' object has no attribute 'lin_l

### ISSUE THREAD

**Issue by 1234238** [LFhase/GIA-HAO#4]
Hello, when I run the RGAT model, I encountered an error AttributeError: 'RGATConv' object has no attribute 'lin_l'. Is there something wrong with this part?

**Comment by LFhase** [comment]
Hi could you double check whether the version of pytorch geometric  matches with that in README?

**Comment by 1234238** [comment]
My version is 2.3.1, do I need to roll back to a previous version? Thank you for your response.

> Hi could you double check whether the version of pytorch geometric matches with that in README?

**Comment by LFhase** [comment]
> My version is 2.3.1, do I need to roll back to a previous version? Thank you for your response.
> 
> > Hi could you double check whether the version of pytorch geometric matches with that in README?

The code is written with the version of 1.7.2. You may roll back to the old version, or try to modify the code a bit for the updated version : )

**Comment by LFhase** [comment]
Hi I'm gonna close the issue if there's not a further question. Please feel free to reopen it anyhow!
